Fix image paths so they work with path prefix
eclipse-theia/theia-website pull request #540
Opened 2024-04-04 07:20 UTC by planger

Referencing images with a URL starting with `/` will always default to the root. This however won't work if we host the page in a folder. As we use plain HTML tags in the markdown, probably the easiest fix is to use relative image links instead.

This change turns all root paths for images into relative paths.

2024-04-04 12:23 UTC, xai commented
> @xai Can you please take a look at this PR and let me know what you think? If you find a better solution for fixing the links and images so they work in the previews, please let me know. Thank you!

Looks good to me, I am not aware of a better approach than relative links for the markdown pages.

However, it looks like we still have several pages that use hard-coded absolute links to the theia-ide.org domain, see `git grep '](https://theia-ide.org/'`. They won't be broken in the preview but link to the production site targets instead of ages from the preview. Should we change them also into relative links?

2024-04-04 12:31 UTC, planger commented
Thanks @xai! Good idea! I've replaced them in a68be8f. Can you please verify whether all links still work?
I noticed there are a few broken links before this change, but I left them for now. We should fix them in a separate PR though.

2024-04-04 12:55 UTC, xai requested changes
Looks pretty good, just very few broken links left.

2024-04-04 12:55 UTC, xai commented on src/docs/blueprint_documentation.md
> +The Theia IDE is based on the Theia platform, which is a flexible and adaptable platform for build tools and IDEs. Therefore, you can adapt the feature set and general appearance of the Theia IDE to
```suggestion
The Theia IDE is based on the Theia platform, which is a flexible and adaptable platform for build tools and IDEs. Therefore, you can adapt the feature set and general appearance of the Theia IDE to your custom requirements with almost no limits. The Theia platform provides two mechanism to add your custom extensions: VS Code extensions and Theia extensions. Please have a look at the [overview about Theia extension capabilities](../extensions/) for details. When assembling a product such as the Theia IDE, you can freely decide, which VS Code extensions and Theia extensions are part of it and thereby influence the feature set of your custom product. The following two sections describe how to modify which [VS Code Extensions](#updating-bundled-vs-code-extensions) and which [Theia extensions](#customizing-theia-extensions) are part of your product. Please also note that you can allow users of a Theia-based tool to [install VS Code extensions at runtime](../user_install_vscode_extensions/).
```

2024-04-04 12:55 UTC, xai commented on src/docs/enhanced_tab_bar_preview.md
> +<img src="../enhanced-preview-custom.png" alt="A screenshot of the customized enhanced preview in Theia" style="max-width: 525px">
```suggestion
<img src="../../enhanced-preview-custom.png" alt="A screenshot of the customized enhanced preview in Theia" style="max-width: 525px">
```

2024-04-04 12:55 UTC, xai commented on src/docs/json_rpc.md
> +To dig more into ContributionProvider see this [section](../Services_and_Contributions#contribution-providers).
```suggestion
To dig more into ContributionProvider see this [section](../services_and_contributions#contribution-providers).
```

2024-04-04 12:55 UTC, xai commented on src/docs/json_rpc.md
> +See more information about how events work in theia [here](../Events#events).
```suggestion
See more information about how events work in theia [here](../events#events).
```

2024-04-04 12:55 UTC, xai commented on src/docs/user_getting_started.md
> +Please note that you can also [use the Theia IDE as a basis to create your own custom product](blueprint_documentation/).
```suggestion
Please note that you can also [use the Theia IDE as a basis to create your own custom product](../blueprint_documentation/).
```

2024-04-04 13:07 UTC, xai requested changes
Caught another two, sorry.

2024-04-04 13:07 UTC, xai commented on src/docs/getting_started.md
> +If you are unsure what Theia is, how it compares to other technologies or how to migrate Eclipse-based tools to it, please have a look at [resource section](../resources/).
```suggestion
If you are unsure what Theia is, how it compares to other technologies or how to migrate Eclipse-based tools to it, please have a look at [resource section](../../resources/).
```

2024-04-04 13:07 UTC, xai commented on src/docs/getting_started.md
> +Theia is an open community, and we are glad to help you. You can ask questions using our [public community forum](https://github.com/eclipse-theia/theia/discussions), you can [report bugs and feature
```suggestion
Theia is an open community, and we are glad to help you. You can ask questions using our [public community forum](https://github.com/eclipse-theia/theia/discussions), you can [report bugs and feature requests](https://github.com/eclipse-theia/theia/issues/new/choose), and you can get [professional support, consulting and implementation services](../../support/) for building products based on Theia.
```

2024-04-04 13:13 UTC, planger commented
Thank you, I think I addressed the additional ones you found. Can you please do one more check? It clearly seems four eyes are better, even though I'm using a link checker :-)

2024-04-04 13:19 UTC, xai approved these changes
LGTM! All broken links have been fixed.

2024-04-09 08:17 UTC, JonasHelming approved these changes
LGTM!

2024-04-09 08:31 UTC, merged