Provide rough documentation on widgets, see issue #26
eclipse-theia/theia-website pull request #61
Opened 2019-09-20 18:59 UTC by alex0711

Provide a documentation regarding how to contribute views and dialogs in Theia.

Explained are: dialogs and views using plain DOM manipulation and React, inversify, css variables and themes.

The documentation regarding views is far from being complete but i think it's at least a start.

2019-09-21 16:21 UTC, vince-fugnitto commented on src/docs/Views.mdx
> +Especially non-complex dialogs can be easily implemented without an UI library. For example, Theia's "About" dialog is an example for this category. Let's start by defining the Menu Contribution and
typo - `clase` should be `class`

2019-09-21 16:29 UTC, vince-fugnitto commented on src/docs/Views.mdx
> +For reference, you can find all the variables in [variables-dark.useable.css](https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/style/variables-dark.useable.css) (or the respec
The link to the main Theia repo is outdated.
https://github.com/eclipse-theia/theia/blob/master/packages/core/src/browser/style/variables-dark.useable.css

2020-01-07 15:05 UTC, jankeromnes commented
Hi @alex0711, many thanks for contributing to Theia's documentation! 💯

Just to make sure, are you planning to continue working on this Pull Request, or would you like someone else to take over from here? 🙂

2020-01-13 20:17 UTC, alex0711 commented
@jankeromnes i won't be able to work on this any time soon - would be great if someone else could continue this part of the documentation :)

2020-01-14 02:59 UTC, akosyakov commented on src/docs/Views.mdx
> +    messageNode.setAttribute('style', 'font-family: var(--theia-ui-font-family); color: var(--theia-ui-font-color1);');
there is no such color styles anymore

2020-11-06 20:28 UTC, marcdumais-work requested changes
This repository was recently re-licensed (https://github.com/theia-ide/theia-website/pull/128/commits/441eac118227ed4920b66fe1619122f8a7659d45). I think we would need to obtain permission from this PR's contributor(s) to use/merge it, under the new license. 

cc: @JonasHelming

2022-01-26 20:21 UTC, alxflam commented
@marcdumais-work I guess this PR is obsolete with the recent PR #214 which covers pretty much everything i had in my draft here (also my draft is pretty outdated). Agree (then i'd close the PR) or do you want to keep it open?

2022-01-26 20:22 UTC, JonasHelming commented
> @marcdumais-work I guess this PR is obsolete with the recent PR #214 which covers pretty much everything i had in my draft here (also my draft is pretty outdated). Agree (then i'd close the PR) or do you want to keep it open?

Thanks for coming back. I believe we can close this, though, as you suggested.

2022-01-26 20:33 UTC, alxflam commented
@JonasHelming  :thumbsup: closing.

2022-01-26 20:33 UTC, closed without merging